import { Task, SubjectInfo, StudyScheduleItem, AssignmentProject, FocusSessionLog, ActivityLog, AppPreferences } from '../types';

export const DEFAULT_SUBJECTS: SubjectInfo[] = [
  { id: 'math', name: 'Calculus & Linear Algebra', color: '#6366f1', icon: 'Calculator' },
  { id: 'cs', name: 'Computer Science', color: '#06b6d4', icon: 'Code' },
  { id: 'physics', name: 'Physics & Mechanics', color: '#8b5cf6', icon: 'Atom' },
  { id: 'lit', name: 'Literature & Composition', color: '#ec4899', icon: 'BookOpen' },
  { id: 'econ', name: 'Microeconomics', color: '#10b981', icon: 'TrendingUp' },
  { id: 'bio', name: 'Molecular Biology', color: '#f59e0b', icon: 'Dna' },
];

const getTodayString = (offsetDays = 0) => {
  const d = new Date();
  d.setDate(d.getDate() + offsetDays);
  return d.toISOString().split('T')[0];
};

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task-1',
    title: 'Complete Problem Set #4 (Multivariable Derivatives)',
    subject: 'Calculus & Linear Algebra',
    priority: 'urgent',
    status: 'pending',
    dueDate: getTodayString(1),
    dueTime: '17:00',
    estimatedMinutes: 90,
    createdAt: new Date(Date.now() - 3600000 * 24).toISOString(),
    notes: 'Focus on partial derivatives and gradient vectors (Problems 12-25 in Stewart Calculus)',
    tags: ['Homework', 'Exam Prep'],
  },
  {
    id: 'task-2',
    title: 'Implement Dijkstra’s Algorithm in Python',
    subject: 'Computer Science',
    priority: 'high',
    status: 'pending',
    dueDate: getTodayString(2),
    dueTime: '23:59',
    estimatedMinutes: 120,
    createdAt: new Date(Date.now() - 3600000 * 30).toISOString(),
    notes: 'Include priority queue (heapq) implementation and edge case unit tests for disconnected graphs.',
    tags: ['Lab', 'Algorithms'],
  },
  {
    id: 'task-3',
    title: 'Physics Lab Report: Rotational Dynamics & Torque',
    subject: 'Physics & Mechanics',
    priority: 'high',
    status: 'pending',
    dueDate: getTodayString(3),
    dueTime: '14:00',
    estimatedMinutes: 150,
    createdAt: new Date(Date.now() - 3600000 * 48).toISOString(),
    notes: 'Plot angular acceleration vs torque graph with error bars in Python or Excel.',
    tags: ['Lab Report'],
  },
  {
    id: 'task-4',
    title: 'Annotate Chapter 4-6 of "To Kill a Mockingbird"',
    subject: 'Literature & Composition',
    priority: 'medium',
    status: 'completed',
    dueDate: getTodayString(0),
    dueTime: '10:00',
    estimatedMinutes: 60,
    completedAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    createdAt: new Date(Date.now() - 3600000 * 50).toISOString(),
    notes: 'Highlight themes of moral growth and racial injustice.',
    tags: ['Reading'],
  },
  {
    id: 'task-5',
    title: 'Review Supply & Demand Elasticity Formulas',
    subject: 'Microeconomics',
    priority: 'medium',
    status: 'pending',
    dueDate: getTodayString(4),
    dueTime: '19:00',
    estimatedMinutes: 45,
    createdAt: new Date(Date.now() - 3600000 * 12).toISOString(),
    notes: 'Practice cross-price elasticity and income elasticity calculations.',
    tags: ['Flashcards', 'Review'],
  },
  {
    id: 'task-6',
    title: 'Organize Biology Chapter Flashcards for Mitosis vs Meiosis',
    subject: 'Molecular Biology',
    priority: 'low',
    status: 'completed',
    dueDate: getTodayString(-1),
    dueTime: '16:00',
    estimatedMinutes: 30,
    completedAt: new Date(Date.now() - 3600000 * 20).toISOString(),
    createdAt: new Date(Date.now() - 3600000 * 72).toISOString(),
    notes: 'Review stages: Prophase, Metaphase, Anaphase, Telophase.',
    tags: ['Notes'],
  },
];

export const INITIAL_SCHEDULE: StudyScheduleItem[] = [
  {
    id: 'sched-1',
    day: 'Monday',
    date: getTodayString(0),
    startTime: '09:00',
    endTime: '10:30',
    subject: 'Calculus & Linear Algebra',
    topic: 'Partial Derivatives & Chain Rule Practice',
    taskType: 'deep_work',
    completed: true,
    notes: 'Covered problems 1 through 8.',
  },
  {
    id: 'sched-2',
    day: 'Monday',
    date: getTodayString(0),
    startTime: '10:45',
    endTime: '12:00',
    subject: 'Computer Science',
    topic: 'Graph Data Structures & Min-Heap Review',
    taskType: 'practice',
    completed: false,
    notes: 'Prep for Dijkstra assignment.',
  },
  {
    id: 'sched-3',
    day: 'Monday',
    date: getTodayString(0),
    startTime: '14:00',
    endTime: '15:30',
    subject: 'Physics & Mechanics',
    topic: 'Moment of Inertia Calculations & Lab Data Analysis',
    taskType: 'deep_work',
    completed: false,
    notes: 'Calculate percent errors for cylindrical disk.',
  },
  {
    id: 'sched-4',
    day: 'Tuesday',
    date: getTodayString(1),
    startTime: '09:30',
    endTime: '11:00',
    subject: 'Literature & Composition',
    topic: 'Drafting Thesis Statement for Comparative Essay',
    taskType: 'reading',
    completed: false,
  },
  {
    id: 'sched-5',
    day: 'Tuesday',
    date: getTodayString(1),
    startTime: '13:00',
    endTime: '14:30',
    subject: 'Microeconomics',
    topic: 'Consumer Surplus and Deadweight Loss Problem Solving',
    taskType: 'revision',
    completed: false,
  },
];

export const INITIAL_ASSIGNMENT_PROJECT: AssignmentProject = {
  id: 'proj-1',
  title: '10-Page Research Paper: Renewable Energy Transition Economics',
  subject: 'Microeconomics',
  dueDate: getTodayString(12),
  complexity: 'major_project',
  description: 'Comprehensive research paper analyzing subsidies, grid parity, and economic barriers to solar & wind adoption.',
  createdAt: new Date().toISOString(),
  steps: [
    {
      id: 'step-1',
      title: 'Formulate Thesis Statement & Research Scope',
      phase: 'Research & Planning',
      estimatedHours: 3,
      suggestedDeadline: getTodayString(2),
      completed: true,
      details: 'Define primary research question on levelized cost of energy (LCOE).',
    },
    {
      id: 'step-2',
      title: 'Literature Review & Gather 8 Peer-Reviewed Sources',
      phase: 'Research & Planning',
      estimatedHours: 5,
      suggestedDeadline: getTodayString(4),
      completed: true,
      details: 'Collect data from NREL, EIA, and journal articles on grid infrastructure.',
    },
    {
      id: 'step-3',
      title: 'Create Detailed Section-by-Section Outline',
      phase: 'Research & Planning',
      estimatedHours: 2.5,
      suggestedDeadline: getTodayString(6),
      completed: false,
      details: 'Outline Introduction, Market Analysis, Policy Interventions, and Conclusion.',
    },
    {
      id: 'step-4',
      title: 'Write First Full Draft (Sections 1 through 4)',
      phase: 'Drafting & Execution',
      estimatedHours: 6,
      suggestedDeadline: getTodayString(8),
      completed: false,
      details: 'Focus on flow and arguments without getting bogged down by micro-edits.',
    },
    {
      id: 'step-5',
      title: 'Write Data Analysis & Policy Discussion Sections',
      phase: 'Drafting & Execution',
      estimatedHours: 5,
      suggestedDeadline: getTodayString(9),
      completed: false,
      details: 'Include charts comparing solar PV vs fossil fuel capital expenditures.',
    },
    {
      id: 'step-6',
      title: 'Peer Review & Self-Editing for Flow, Argument Strength',
      phase: 'Review & Refinement',
      estimatedHours: 3,
      suggestedDeadline: getTodayString(10),
      completed: false,
      details: 'Check transition paragraphs and ensure all claims cite empirical data.',
    },
    {
      id: 'step-7',
      title: 'Format Citations (APA 7th Edition) & Final Proofreading',
      phase: 'Final Submission',
      estimatedHours: 2,
      suggestedDeadline: getTodayString(12),
      completed: false,
      details: 'Verify reference list, title page, headers, and submit PDF to portal.',
    },
  ],
};

export const INITIAL_LOGS: ActivityLog[] = [
  {
    id: 'log-1',
    type: 'task_completed',
    message: 'Completed task: "Annotate Chapter 4-6 of To Kill a Mockingbird"',
    timestamp: new Date(Date.now() - 3600000 * 4).toISOString(),
  },
  {
    id: 'log-2',
    type: 'focus_completed',
    message: 'Finished 25-minute Pomodoro focus session on Calculus',
    timestamp: new Date(Date.now() - 3600000 * 6).toISOString(),
  },
  {
    id: 'log-3',
    type: 'schedule_generated',
    message: 'AI Study Planner generated weekly timetable with 12 focus blocks',
    timestamp: new Date(Date.now() - 3600000 * 24).toISOString(),
  },
  {
    id: 'log-4',
    type: 'task_created',
    message: 'Added urgent task: "Complete Problem Set #4"',
    timestamp: new Date(Date.now() - 3600000 * 24).toISOString(),
  },
];

export const INITIAL_PREFERENCES: AppPreferences = {
  theme: 'light',
  userName: 'Alex',
  enableSounds: true,
};

export const INITIAL_FOCUS_LOGS: FocusSessionLog[] = [
  {
    id: 'f-1',
    timestamp: new Date(Date.now() - 3600000 * 6).toISOString(),
    durationMinutes: 25,
    subject: 'Calculus & Linear Algebra',
    mode: 'pomodoro',
  },
  {
    id: 'f-2',
    timestamp: new Date(Date.now() - 3600000 * 30).toISOString(),
    durationMinutes: 25,
    subject: 'Computer Science',
    mode: 'pomodoro',
  },
  {
    id: 'f-3',
    timestamp: new Date(Date.now() - 3600000 * 54).toISOString(),
    durationMinutes: 25,
    subject: 'Physics & Mechanics',
    mode: 'pomodoro',
  },
];
